site_name: 'AR Assistant Documentation'
site_url: https://ar.github.io
repo_name: 'ar.github.io'
repo_url: 'https://github.com/tempnamefornow/ar.github.io'

############################################################################################

nav:
# Homepage
  - Project Documentation:
    - Scoping:
      - v0.0.2: project_documentation/scoping/v0.0.2.md
      - v0.0.1: project_documentation/scoping/v0.0.1.md
      - Computer Vision Models:  
        - v0.0.1: project_documentation/scoping/computer_vision_models/v0.0.1.md
      - Large Language Models:   
        - v0.0.1: project_documentation/scoping/large_language_models/v0.0.1.md
      - Text To Spech Models:
        - v0.0.1: project_documentation/scoping/text_to_speech_models/v0.0.1.md
      - Edge Devices:            
        - v0.0.1: project_documentation/scoping/edge_devices/v0.0.1.md
      - Speech To Text Models:
        - v0.0.1: project_documentation/scoping/speech_to_text_models/v0.0.1.md
  - Developer Notes: 
    - developer_notes/index.md
    - Operations:
      - Github: 
        - Git Introduction: developer_notes/operations/git/git_intro.md
        - Actions: developer_notes/operations/git/git_actions.md
      - MLOps: 
        - Overview:  developer_notes/operations/mlops/overview.md
      - Project Planning: 
        - Project Scoping:
          - Overview:  developer_notes/operations/project_planning/scoping/overview.md
          - Human Level Performance (HLP):  developer_notes/operations/project_planning/scoping/hlp.md

    - Engineering:
      - Orchestration:
        - Apache Airflow: developer_notes/engineering/orchestration/airflow.md
      - Data Validation:
        - TFDV: developer_notes/engineering/data_validation/tfdv.md

############################################################################################

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.annotate 
  icon:
    admonition: 
      example: fontawesome/solid/flask
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - mkdocs-video:
      is_video: True
      video_muted: False
      video_controls: True
      css_style:
        width: "50%"